classified/urls.py
from django.urls import path
from classified import views

urlpatterns = [
    path('list/', views.ClassifiedList.as_view(), name='list'),
    path('<int:pk>/', views.ClassifiedDetail.as_view(), name='detail'),
]

testproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classified/', include(('classified.urls', 'classified'), namespace='classified')),
]

classified/models.py
from django.db import models
from django.contrib.auth.models import User

NEW = 0
PROCESSING = 1

STATES = ((NEW, 'New'), (PROCESSING, 'Proccessing'))

class City(models.Model):
    """Город к которому объявления относится"""

    # Могут быть города с одинаковыми названиями
    # можно сделать комбинированный ключ из 
    # страны, области и города
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Города'


class Classified(models.Model):
    """Объявление"""
    header = models.CharField(max_length=255)
    body = models.TextField()
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    views = models.PositiveIntegerField() # Количество просмотров объявления

    def __str__(self):
        return self.header

    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'


class ViewCounter(models.Model):
    """Счетчик просмотра объявлений.
    При просмотре объявления добавляется запись
    которая в последующем будет обработан Celery
    """
    classified = models.ForeignKey(Classified, on_delete=models.CASCADE)
    state = models.PositiveIntegerField(choices=STATES)

    def __str__(self):
        return "{} - {}".format(self.classified, self.state)

    class Meta:
        verbose_name = 'Счетчик'
        verbose_name_plural = 'Счетчики'

classifield/models.py
from django.db import models
from django.contrib.auth.models import User


class City(models.Model):
    """Город к которому объявления относится"""
    # Могут быть города с одинаковымы назаваниями
    # можно сделать комбинированный ключ из 
    # страны, области и города
    name = models.Model(max_length=255, unique=True)

    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Города'


class Classfield(models.Model):
    """Объявление"""
    header = models.CharField()
    body = models.TextField()
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'


class Counter(models.Model):
    """Счетчик просмотра объявлений"""
    classfield = models.ForeignKey(Classfield, on_delete=models.CASCADE)
    value = models.PositiveIntegerField()

    class Meta:
        verbose_name = 'Счетчик'
        verbose_name_plural = 'Счетчики'

classified/views.py
from django.shortcuts import render
from django.views.generic import (
    DetailView,
    ListView,
)

from classified.models import (
    Classified,
    ViewCounter,
    NEW
)


class ClassifiedList(ListView):
    model = Classified
    paginate_by = 10


class ClassifiedDetail(DetailView):
    model = Classified

    def get_object(self):
        obj = super().get_object()
        ViewCounter.objects.create(classified=obj, state=NEW)
        return obj

classified/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <title>Classified</title>

</head>
<body>
    <header>
        <div class="navbar navbar-dark bg-dark box-shadow">
            <nav class="nav">
                <a class="nav-link" href="#">Link</a>
                <a class="nav-link" href="#">Link</a>
            </nav>
        </div>
    </header>

    <main role="main">
        <div class="album py-5 bg-light">
            <div class="container">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </main>
</body>
</html>

classified/templates/classified/classified_detail.html
{% extends '../base.html' %}

{% block content %}
{% endblock %}

classified/templates/classified/classified_list.html
{% extends '../base.html' %}

{% block content %}
<div class="row">
    {% for obj in object_list %}
    <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p class="card-title">{{obj.header}}</p>
                    <p class="card-text">{{obj.body}}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'classified:detail' pk=obj.pk %}" class="btn btn-sm btn-outline-secondary">
                                view
                            </a>
                        </div>
                        <small class="text-muted">{{obj.views}}</small>
                    </div>
                </div>
            </div>
    </div>
    {% endfor %}
</div>
{% endblock %}